version: 2.1

executors:
  rust-executor:
    docker:
      - image: cimg/rust:1.92

jobs:
  build-test-clippy:
    executor: rust-executor
    steps:
      - checkout
      - run:
          name: Check version
          command: rustc --version && cargo --version
      - run:
          name: Build
          command: cargo build
      - run:
          name: Test
          command: cargo test
      - run:
          name: Clippy
          command: cargo clippy -- -D warnings

  publish:
    executor: rust-executor
    steps:
      - checkout
      - run:
          name: Publish to Crates.io
          command: cargo publish --token $CARGO_TOKEN

workflows:
  build_and_publish:
    jobs:
      - build-test-clippy:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - build-test-clippy
          when:
            condition:
              equal: [main, << pipeline.git.branch >>]
              equal: [/^v.*/, << pipeline.git.tag >>]
